
package com.spartacus.eArchiveWeb.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Integration10Soap", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Integration10Soap {


    /**
     * Ortak: session modul tipine uygun e-donusum mukellef listesini getirir | eInvoice/eArchive: eFatura mukellefleri, eDespatch: eIrsaliye mukellefleri
     * 
     * @param userToken
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.ArrayOfEInvoiceEnabledCompany
     */
    @WebMethod(operationName = "GetFullUserList", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetFullUserList")
    @WebResult(name = "GetFullUserListResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetFullUserList", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetFullUserList")
    @ResponseWrapper(localName = "GetFullUserListResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetFullUserListResponse")
    public ArrayOfEInvoiceEnabledCompany getFullUserList(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken);

    /**
     * Ortak: eFatura, eIrsaliye ve eBilet icin vkn/tckn bilgilerini getirir
     * 
     * @param userToken
     * @param taxId
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.ArrayOfEInvoiceEnabledCompany
     */
    @WebMethod(operationName = "GetUserInfoByTaxId", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetUserInfoByTaxId")
    @WebResult(name = "GetUserInfoByTaxIdResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetUserInfoByTaxId", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetUserInfoByTaxId")
    @ResponseWrapper(localName = "GetUserInfoByTaxIdResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetUserInfoByTaxIdResponse")
    public ArrayOfEInvoiceEnabledCompany getUserInfoByTaxId(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "taxId", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String taxId);

    /**
     * Ortak: Modul ilgili belge olusturulmadan once vkn/tckn bilgisini kontrol eder
     * 
     * @param userToken
     * @param taxId
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CheckUserInfoByTaxId", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/CheckUserInfoByTaxId")
    @WebResult(name = "CheckUserInfoByTaxIdResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "CheckUserInfoByTaxId", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.CheckUserInfoByTaxId")
    @ResponseWrapper(localName = "CheckUserInfoByTaxIdResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.CheckUserInfoByTaxIdResponse")
    public boolean checkUserInfoByTaxId(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "taxId", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String taxId);

    /**
     * Ortak: session modul tipine uygun e-donusum mukellef listesini getirir | eInvoice/eArchive: eFatura mukellefleri, eDespatch: eIrsaliye mukellefleri
     * 
     * @param userToken
     * @param includeDeleted
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.ArrayOfCompanyInformation
     */
    @WebMethod(operationName = "GetCompanyPostBoxList", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetCompanyPostBoxList")
    @WebResult(name = "GetCompanyPostBoxListResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetCompanyPostBoxList", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetCompanyPostBoxList")
    @ResponseWrapper(localName = "GetCompanyPostBoxListResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetCompanyPostBoxListResponse")
    public ArrayOfCompanyInformation getCompanyPostBoxList(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "includeDeleted", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        boolean includeDeleted);

    /**
     * Ortak: Arsiv ya da faturanin tekil degeri uzerinden html bilgisini getirir
     * 
     * @param userToken
     * @param invoiceUUID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInvoiceHtmlByUUID", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetInvoiceHtmlByUUID")
    @WebResult(name = "GetInvoiceHtmlByUUIDResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetInvoiceHtmlByUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetInvoiceHtmlByUUID")
    @ResponseWrapper(localName = "GetInvoiceHtmlByUUIDResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetInvoiceHtmlByUUIDResponse")
    public String getInvoiceHtmlByUUID(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "invoiceUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String invoiceUUID);

    /**
     * Ortak: Dokuman tekil anahtar degeri uzerinden oturum bilgisindeki modul degerine gore html bilgisini getirir
     * 
     * @param userToken
     * @param documentUUID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCommonDocumentHtmlByUUID", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetCommonDocumentHtmlByUUID")
    @WebResult(name = "GetCommonDocumentHtmlByUUIDResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetCommonDocumentHtmlByUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetCommonDocumentHtmlByUUID")
    @ResponseWrapper(localName = "GetCommonDocumentHtmlByUUIDResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetCommonDocumentHtmlByUUIDResponse")
    public String getCommonDocumentHtmlByUUID(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "documentUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String documentUUID);

    /**
     * Ortak: Arsiv ya da faturanin tekil degeri uzerinden imzali xml bilgisini getirir
     * 
     * @param userToken
     * @param invoiceUUID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInvoiceSignedXmlByUUID", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetInvoiceSignedXmlByUUID")
    @WebResult(name = "GetInvoiceSignedXmlByUUIDResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetInvoiceSignedXmlByUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetInvoiceSignedXmlByUUID")
    @ResponseWrapper(localName = "GetInvoiceSignedXmlByUUIDResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetInvoiceSignedXmlByUUIDResponse")
    public String getInvoiceSignedXmlByUUID(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "invoiceUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String invoiceUUID);

    /**
     * Ortak: Dokuman tekil degeri uzerinden imzali xml bilgisini getirir
     * 
     * @param userToken
     * @param documentUUID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCommonDocumentSignedXmlByUUID", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetCommonDocumentSignedXmlByUUID")
    @WebResult(name = "GetCommonDocumentSignedXmlByUUIDResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetCommonDocumentSignedXmlByUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetCommonDocumentSignedXmlByUUID")
    @ResponseWrapper(localName = "GetCommonDocumentSignedXmlByUUIDResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetCommonDocumentSignedXmlByUUIDResponse")
    public String getCommonDocumentSignedXmlByUUID(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "documentUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String documentUUID);

    /**
     * Ortak: Sistemde fatura bilgisi saklanmadan once sema, sematron ve is kurallari denetlenir
     * 
     * @param userToken
     * @param invoice
     */
    @WebMethod(operationName = "CheckInvoice", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/CheckInvoice")
    @RequestWrapper(localName = "CheckInvoice", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.CheckInvoice")
    @ResponseWrapper(localName = "CheckInvoiceResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.CheckInvoiceResponse")
    public void checkInvoice(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "invoice", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
                NetleEFatura invoice);

    /**
     * Ortak: Sistemde fatura bilgisi saklanmadan once sema, sematron ve is kurallari denetlenir
     * 
     * @param userToken
     * @param despatchAdvice
     */
    @WebMethod(operationName = "CheckDespatchAdvice", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/CheckDespatchAdvice")
    @RequestWrapper(localName = "CheckDespatchAdvice", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.CheckDespatchAdvice")
    @ResponseWrapper(localName = "CheckDespatchAdviceResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.CheckDespatchAdviceResponse")
    public void checkDespatchAdvice(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "despatchAdvice", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
                NetleEIrsaliye despatchAdvice);

    /**
     * Ortak: Sistemde dokuman bilgisi saklanmadan once sema, sematron ve is kurallari denetlenir
     * 
     * @param userToken
     * @param document
     */
    @WebMethod(operationName = "CheckCommonDocument", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/CheckCommonDocument")
    @RequestWrapper(localName = "CheckCommonDocument", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.CheckCommonDocument")
    @ResponseWrapper(localName = "CheckCommonDocumentResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.CheckCommonDocumentResponse")
    public void checkCommonDocument(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "document", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
                NetleEFatura document);

    /**
     * Ortak: NetleEFatura nesnesinden VKN degeri algilanarak eArsiv ya da eFatura goruntusu html olarak hazirlanir
     * 
     * @param userToken
     * @param invoice
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInvoiceHtmlByNetleFatura", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetInvoiceHtmlByNetleFatura")
    @WebResult(name = "GetInvoiceHtmlByNetleFaturaResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetInvoiceHtmlByNetleFatura", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetInvoiceHtmlByNetleFatura")
    @ResponseWrapper(localName = "GetInvoiceHtmlByNetleFaturaResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetInvoiceHtmlByNetleFaturaResponse")
    public String getInvoiceHtmlByNetleFatura(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "invoice", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
                NetleEFatura invoice);

    /**
     * Ortak: NetleEFatura nesnesinden VKN degeri algilanarak Kaynak Dokuman Turune gore html olarak hazirlanir
     * 
     * @param userToken
     * @param document
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCommonDocumentHtmlByNetleFatura", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetCommonDocumentHtmlByNetleFatura")
    @WebResult(name = "GetCommonDocumentHtmlByNetleFaturaResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetCommonDocumentHtmlByNetleFatura", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetCommonDocumentHtmlByNetleFatura")
    @ResponseWrapper(localName = "GetCommonDocumentHtmlByNetleFaturaResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetCommonDocumentHtmlByNetleFaturaResponse")
    public String getCommonDocumentHtmlByNetleFatura(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "document", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
                NetleEFatura document);

    /**
     * Ortak: ilgili token degerine gore NetleEFatura biciminde e-fatura ya da e-arsiv dokumani yukler
     * 
     * @param userToken
     * @param prefix
     * @param invoice
     * @param uuid
     */
    @WebMethod(operationName = "UploadInvoice", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/UploadInvoice")
    @RequestWrapper(localName = "UploadInvoice", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.UploadInvoice")
    @ResponseWrapper(localName = "UploadInvoiceResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.UploadInvoiceResponse")
    public void uploadInvoice(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "uuid", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String uuid,
        @WebParam(name = "prefix", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String prefix,
        @WebParam(name = "invoice", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
                NetleEFatura invoice);

    /**
     * Ortak: ilgili token degerine gore NetleEFatura biciminde e-dokumani yukler
     * 
     * @param userToken
     * @param documentUUID
     * @param prefix
     * @param document
     */
    @WebMethod(operationName = "UploadCommonDocument", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/UploadCommonDocument")
    @RequestWrapper(localName = "UploadCommonDocument", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.UploadCommonDocument")
    @ResponseWrapper(localName = "UploadCommonDocumentResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.UploadCommonDocumentResponse")
    public void uploadCommonDocument(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "documentUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String documentUUID,
        @WebParam(name = "prefix", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String prefix,
        @WebParam(name = "document", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
                NetleEFatura document);

    /**
     * Ortak: ilgili token degerine ve dokuman turune gore XML biciminde e-dokumani yukler
     * 
     * @param userToken
     * @param documentUUID
     * @param prefix
     * @param docType
     * @param documentXML
     */
    @WebMethod(operationName = "UploadCommonDocumentXML", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/UploadCommonDocumentXML")
    @RequestWrapper(localName = "UploadCommonDocumentXML", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.UploadCommonDocumentXML")
    @ResponseWrapper(localName = "UploadCommonDocumentXMLResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.UploadCommonDocumentXMLResponse")
    public void uploadCommonDocumentXML(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "documentUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String documentUUID,
        @WebParam(name = "prefix", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String prefix,
        @WebParam(name = "documentXML", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String documentXML,
        @WebParam(name = "docType", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        GetDocumentType docType);

    /**
     * Ortak: ilgili token degerine gore NetleEFatura biciminde e-fatura ya da e-arsiv dokumanini getirir
     * 
     * @param userToken
     * @param uuid
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.NetleEFatura
     */
    @WebMethod(operationName = "DownloadInvoice", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/DownloadInvoice")
    @WebResult(name = "DownloadInvoiceResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "DownloadInvoice", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.DownloadInvoice")
    @ResponseWrapper(localName = "DownloadInvoiceResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.DownloadInvoiceResponse")
    public NetleEFatura downloadInvoice(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "uuid", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String uuid);

    /**
     * Ortak: ilgili token degerine gore NetleEFatura biciminde ortak dokumani getirir
     * 
     * @param userToken
     * @param documentUUID
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.NetleEFatura
     */
    @WebMethod(operationName = "DownloadCommonDocument", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/DownloadCommonDocument")
    @WebResult(name = "DownloadCommonDocumentResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "DownloadCommonDocument", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.DownloadCommonDocument")
    @ResponseWrapper(localName = "DownloadCommonDocumentResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.DownloadCommonDocumentResponse")
    public NetleEFatura downloadCommonDocument(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "documentUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String documentUUID);

    /**
     * Ortak: ilgili token degerine gore UUID seklinde verilen efatura ya da earsiv dokumanlarini eposta ile gonderir
     * 
     * @param userToken
     * @param info
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendEmailByUUID", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/SendEmailByUUID")
    @WebResult(name = "SendEmailByUUIDResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "SendEmailByUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.SendEmailByUUID")
    @ResponseWrapper(localName = "SendEmailByUUIDResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.SendEmailByUUIDResponse")
    public String sendEmailByUUID(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "info", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        InvoiceSendingMailInfo info);

    /**
     * Ortak: SendEmailByUUID yonteminden donen JobId degerine gore durum sorgulama sonucunu getirir
     * 
     * @param userToken
     * @param emailJobId
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.SendingMailResult
     */
    @WebMethod(operationName = "GetEMailStatusById", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetEMailStatusById")
    @WebResult(name = "GetEMailStatusByIdResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetEMailStatusById", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEMailStatusById")
    @ResponseWrapper(localName = "GetEMailStatusByIdResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEMailStatusByIdResponse")
    public SendingMailResult getEMailStatusById(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "emailJobId", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String emailJobId);

    /**
     * Ortak: userToken bazinda son islemde alinan hata mesajini geriye doner
     * 
     * @param userToken
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.SoapExceptionDetail
     */
    @WebMethod(operationName = "GetLastError", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetLastError")
    @WebResult(name = "GetLastErrorResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetLastError", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetLastError")
    @ResponseWrapper(localName = "GetLastErrorResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetLastErrorResponse")
    public SoapExceptionDetail getLastError(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken);

    /**
     * Ortak: ilgili fatura ettn degerine gore akis son bilgisini ve tarihcesini geriye doner
     * 
     * @param userToken
     * @param uuid
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.WFSessionHistories
     */
    @WebMethod(operationName = "GetWorkflowInfoByUUID", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetWorkflowInfoByUUID")
    @WebResult(name = "GetWorkflowInfoByUUIDResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetWorkflowInfoByUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetWorkflowInfoByUUID")
    @ResponseWrapper(localName = "GetWorkflowInfoByUUIDResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetWorkflowInfoByUUIDResponse")
    public WFSessionHistories getWorkflowInfoByUUID(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "uuid", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String uuid);

    /**
     * Ortak: ilgili netle wf guid (tekil) anahtar degerine gore akis son bilgisini ve tarihcesini geriye doner
     * 
     * @param userToken
     * @param wfGUID
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.WFSessionHistories
     */
    @WebMethod(operationName = "GetWorkflowInfoByGUID", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetWorkflowInfoByGUID")
    @WebResult(name = "GetWorkflowInfoByGUIDResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetWorkflowInfoByGUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetWorkflowInfoByGUID")
    @ResponseWrapper(localName = "GetWorkflowInfoByGUIDResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetWorkflowInfoByGUIDResponse")
    public WFSessionHistories getWorkflowInfoByGUID(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "wfGUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String wfGUID);

    /**
     * Ortak: Onayda bekleyen dokumani ilgili aciklama ile kabul et
     * 
     * @param userToken
     * @param reasonDescription
     * @param uuid
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.SoapExceptionDetail
     */
    @WebMethod(operationName = "AcceptInvoiceDocument", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/AcceptInvoiceDocument")
    @WebResult(name = "AcceptInvoiceDocumentResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "AcceptInvoiceDocument", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.AcceptInvoiceDocument")
    @ResponseWrapper(localName = "AcceptInvoiceDocumentResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.AcceptInvoiceDocumentResponse")
    public SoapExceptionDetail acceptInvoiceDocument(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "uuid", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String uuid,
        @WebParam(name = "reasonDescription", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String reasonDescription);

    /**
     * Ortak: onayda bekleyen dokumani ilgili aciklama ile reddet
     * 
     * @param userToken
     * @param reasonDescription
     * @param uuid
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.SoapExceptionDetail
     */
    @WebMethod(operationName = "RejectInvoiceDocument", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/RejectInvoiceDocument")
    @WebResult(name = "RejectInvoiceDocumentResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "RejectInvoiceDocument", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.RejectInvoiceDocument")
    @ResponseWrapper(localName = "RejectInvoiceDocumentResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.RejectInvoiceDocumentResponse")
    public SoapExceptionDetail rejectInvoiceDocument(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "uuid", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String uuid,
        @WebParam(name = "reasonDescription", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String reasonDescription);

    /**
     * Ortak: ilgili token degerine gore PDF goruntusu ile birlikte fatura/arsiv dokumanini yukle
     * 
     * @param userToken
     * @param invoices
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.UploadResult
     */
    @WebMethod(operationName = "UploadUbltrWithPDFLayout", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/UploadUbltrWithPDFLayout")
    @WebResult(name = "UploadUbltrWithPDFLayoutResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "UploadUbltrWithPDFLayout", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.UploadUbltrWithPDFLayout")
    @ResponseWrapper(localName = "UploadUbltrWithPDFLayoutResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.UploadUbltrWithPDFLayoutResponse")
    public UploadResult uploadUbltrWithPDFLayout(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "invoices", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
                ArrayOfUbltrWithPDFLayout invoices);

    /**
     * Ortak: ilgili token degerine ve UUID deger(ler)ine gore PDF dokuman olusturulur.
     * 
     * @param userToken
     * @param pdfInputs
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.ArrayOfUbltrPDFOutput
     */
    @WebMethod(operationName = "GetCommonDocumentPDFByUUIDs", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetCommonDocumentPDFByUUIDs")
    @WebResult(name = "GetCommonDocumentPDFByUUIDsResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetCommonDocumentPDFByUUIDs", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetCommonDocumentPDFByUUIDs")
    @ResponseWrapper(localName = "GetCommonDocumentPDFByUUIDsResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetCommonDocumentPDFByUUIDsResponse")
    public ArrayOfUbltrPDFOutput getCommonDocumentPDFByUUIDs(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "pdfInputs", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
                ArrayOfUbltrPDFInput pdfInputs);

    /**
     * Ortak: ilgili token degerine GIB kullanici listesini ZIP paketi olarak geriye doner
     * 
     * @param userToken
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetCommonUserListAsZIP", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetCommonUserListAsZIP")
    @WebResult(name = "GetCommonUserListAsZIPResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetCommonUserListAsZIP", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetCommonUserListAsZIP")
    @ResponseWrapper(localName = "GetCommonUserListAsZIPResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetCommonUserListAsZIPResponse")
    public byte[] getCommonUserListAsZIP(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken);

    /**
     * e-Arsiv: GIB e gonderilen e-arsiv raporunun ust bilgilerini getirir
     * 
     * @param userToken
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.ArrayOfEArchiveLegalReport
     */
    @WebMethod(operationName = "GetEArcReports", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetEArcReports")
    @WebResult(name = "GetEArcReportsResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetEArcReports", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEArcReports")
    @ResponseWrapper(localName = "GetEArcReportsResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEArcReportsResponse")
    public ArrayOfEArchiveLegalReport getEArcReports(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken);

    /**
     * e-Arsiv: GIB e gonderilen e-arsiv raporunun tekil anahtar uzerinden xml icerigini getirir
     * 
     * @param userToken
     * @param reportId
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.EArchiveLegalReportData
     */
    @WebMethod(operationName = "GetEArcReportById", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetEArcReportById")
    @WebResult(name = "GetEArcReportByIdResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetEArcReportById", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEArcReportById")
    @ResponseWrapper(localName = "GetEArcReportByIdResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEArcReportByIdResponse")
    public EArchiveLegalReportData getEArcReportById(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "reportId", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String reportId);

    /**
     * e-Arsiv: e-arsiv belgesinin durum bilgisini getirir
     * 
     * @param userToken
     * @param eArchiveUUID
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.EArchiveStatus
     */
    @WebMethod(operationName = "GetEArchiveStatus", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetEArchiveStatus")
    @WebResult(name = "GetEArchiveStatusResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetEArchiveStatus", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEArchiveStatus")
    @ResponseWrapper(localName = "GetEArchiveStatusResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEArchiveStatusResponse")
    public EArchiveStatus getEArchiveStatus(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "eArchiveUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String eArchiveUUID);

    /**
     * e-Arsiv: Gonderilen e-arsiv belgesine itiraz ve gib raporuna itiraz edilmis olarak gitmesini saglar
     * 
     * @param userToken
     * @param eArchiveUUID
     * @param objectionDocNumber
     * @param objectionReason
     * @param objectionMethod
     */
    @WebMethod(operationName = "ObjectEArchive", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/ObjectEArchive")
    @RequestWrapper(localName = "ObjectEArchive", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.ObjectEArchive")
    @ResponseWrapper(localName = "ObjectEArchiveResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.ObjectEArchiveResponse")
    public void objectEArchive(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "eArchiveUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String eArchiveUUID,
        @WebParam(name = "objectionDocNumber", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String objectionDocNumber,
        @WebParam(name = "objectionMethod", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String objectionMethod,
        @WebParam(name = "objectionReason", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String objectionReason);

    /**
     * e-Arsiv: Gonderilen e-arsiv belgesini siler ve gib raporuna silinmis olarak gitmesini saglar
     * 
     * @param userToken
     * @param eArchiveUUID
     */
    @WebMethod(operationName = "DeleteEArchive", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/DeleteEArchive")
    @RequestWrapper(localName = "DeleteEArchive", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.DeleteEArchive")
    @ResponseWrapper(localName = "DeleteEArchiveResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.DeleteEArchiveResponse")
    public void deleteEArchive(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "eArchiveUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String eArchiveUUID);

    /**
     * e-Arsiv: Gonderilen e-arsiv belgesini siler ve gib raporuna silinmis olarak gitmesini saglar
     * 
     * @param userToken
     * @param eArchiveUUID
     * @param deleteDate
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.DeleteResult
     */
    @WebMethod(operationName = "DeleteEArchiveWithDate", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/DeleteEArchiveWithDate")
    @WebResult(name = "DeleteEArchiveWithDateResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "DeleteEArchiveWithDate", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.DeleteEArchiveWithDate")
    @ResponseWrapper(localName = "DeleteEArchiveWithDateResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.DeleteEArchiveWithDateResponse")
    public DeleteResult deleteEArchiveWithDate(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "eArchiveUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String eArchiveUUID,
        @WebParam(name = "deleteDate", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        XMLGregorianCalendar deleteDate);

    /**
     * e-Arsiv: Belirlenen kriterlere gore e-arsiv dokumanlarini arar ve geriye tekil UUID degerlerini getirir
     * 
     * @param userToken
     * @param seado
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.ArrayOfGuid
     */
    @WebMethod(operationName = "SearchEArchive", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/SearchEArchive")
    @WebResult(name = "SearchEArchiveResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "SearchEArchive", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.SearchEArchive")
    @ResponseWrapper(localName = "SearchEArchiveResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.SearchEArchiveResponse")
    public ArrayOfGuid searchEArchive(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "seado", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
                SearchEArcDocumentOption seado);

    /**
     * e-Arsiv: Belirlenen tekil anahtarlara gore e-arşiv durum bilgisini ve NetleEFatura nesnesini getirir
     * 
     * @param userToken
     * @param eArchiveUUID
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.EArchiveStatusWithObject
     */
    @WebMethod(operationName = "GetEArchiveStatusByObject", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetEArchiveStatusByObject")
    @WebResult(name = "GetEArchiveStatusByObjectResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetEArchiveStatusByObject", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEArchiveStatusByObject")
    @ResponseWrapper(localName = "GetEArchiveStatusByObjectResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEArchiveStatusByObjectResponse")
    public EArchiveStatusWithObject getEArchiveStatusByObject(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "eArchiveUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String eArchiveUUID);

    /**
     * e-Fatura: Belirlenen kriterlere gore e-fatura dokumanlarini arar ve geriye tekil UUID degerlerini getirir
     * 
     * @param userToken
     * @param sdo
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.ArrayOfDocumentKey
     */
    @WebMethod(operationName = "SearchEInvoice", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/SearchEInvoice")
    @WebResult(name = "SearchEInvoiceResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "SearchEInvoice", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.SearchEInvoice")
    @ResponseWrapper(localName = "SearchEInvoiceResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.SearchEInvoiceResponse")
    public ArrayOfDocumentKey searchEInvoice(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "sdo", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        SearchDocumentOption sdo);

    /**
     * e-Fatura: Belirlenen tekil anahtarlara gore e-fatura dokumanlarini arar ve geriye dokuman bilgilerini getirir
     * 
     * @param userToken
     * @param documentKeys
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.ArrayOfNDocument
     */
    @WebMethod(operationName = "GetEInvoiceDocument", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetEInvoiceDocument")
    @WebResult(name = "GetEInvoiceDocumentResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetEInvoiceDocument", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEInvoiceDocument")
    @ResponseWrapper(localName = "GetEInvoiceDocumentResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEInvoiceDocumentResponse")
    public ArrayOfNDocument getEInvoiceDocument(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "documentKeys", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        ArrayOfDocumentKey documentKeys);

    /**
     * e-Fatura: Belirlenen tekil anahtarlara gore e-fatura dokumanlarini arar ve geriye dokuman bilgilerini getirir
     * 
     * @param userToken
     * @param documentKeys
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.ArrayOfNDocumentWithObject
     */
    @WebMethod(operationName = "GetEInvoiceDocumentByObject", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetEInvoiceDocumentByObject")
    @WebResult(name = "GetEInvoiceDocumentByObjectResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetEInvoiceDocumentByObject", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEInvoiceDocumentByObject")
    @ResponseWrapper(localName = "GetEInvoiceDocumentByObjectResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEInvoiceDocumentByObjectResponse")
    public ArrayOfNDocumentWithObject getEInvoiceDocumentByObject(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "documentKeys", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        ArrayOfDocumentKey documentKeys);

    /**
     * e-Fatura: Belirlenen tekil anahtarlara gore e-fatura uygulama yanitlarini sirasiyla geriye doner
     * 
     * @param userToken
     * @param uuid
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.ArrayOfNAppResponseDocument
     */
    @WebMethod(operationName = "GetEInvoiceAppResponsesByUUID", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetEInvoiceAppResponsesByUUID")
    @WebResult(name = "GetEInvoiceAppResponsesByUUIDResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetEInvoiceAppResponsesByUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEInvoiceAppResponsesByUUID")
    @ResponseWrapper(localName = "GetEInvoiceAppResponsesByUUIDResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEInvoiceAppResponsesByUUIDResponse")
    public ArrayOfNAppResponseDocument getEInvoiceAppResponsesByUUID(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "uuid", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String uuid);

    /**
     * e-Fatura: ihracat faturalarinda gtb disindeki musteri adina gore html goruntusu hazirla
     * 
     * @param userToken
     * @param invoice
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetExportInvoiceHtmlByNetleFatura", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetExportInvoiceHtmlByNetleFatura")
    @WebResult(name = "GetExportInvoiceHtmlByNetleFaturaResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetExportInvoiceHtmlByNetleFatura", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetExportInvoiceHtmlByNetleFatura")
    @ResponseWrapper(localName = "GetExportInvoiceHtmlByNetleFaturaResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetExportInvoiceHtmlByNetleFaturaResponse")
    public String getExportInvoiceHtmlByNetleFatura(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "invoice", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
                NetleEFatura invoice);

    /**
     * e-Fatura: ihracat faturalarinda gtb disindeki musteri adina gore html goruntusu hazirla
     * 
     * @param userToken
     * @param uuid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetExportInvoiceHtmlByUUID", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetExportInvoiceHtmlByUUID")
    @WebResult(name = "GetExportInvoiceHtmlByUUIDResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetExportInvoiceHtmlByUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetExportInvoiceHtmlByUUID")
    @ResponseWrapper(localName = "GetExportInvoiceHtmlByUUIDResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetExportInvoiceHtmlByUUIDResponse")
    public String getExportInvoiceHtmlByUUID(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "uuid", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String uuid);

    /**
     * e-Fatura: Toplu sekilde zarf durum sorgulama islemidir
     * 
     * @param userToken
     * @param docGuids
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.ArrayOfEDocStatus
     */
    @WebMethod(operationName = "GetEnvelopeStatus", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/GetEnvelopeStatus")
    @WebResult(name = "GetEnvelopeStatusResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "GetEnvelopeStatus", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEnvelopeStatus")
    @ResponseWrapper(localName = "GetEnvelopeStatusResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.GetEnvelopeStatusResponse")
    public ArrayOfEDocStatus getEnvelopeStatus(
        @WebParam(name = "userToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userToken,
        @WebParam(name = "docGuids", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
                ArrayOfGuid docGuids);

    /**
     * SEDP:Internal Use
     * 
     * @param moduleType
     * @param taxId
     * @param docType
     * @param documentXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SEDP_SignAndSend", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/SEDP_SignAndSend")
    @WebResult(name = "SEDP_SignAndSendResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "SEDP_SignAndSend", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.SEDPSignAndSend")
    @ResponseWrapper(localName = "SEDP_SignAndSendResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.SEDPSignAndSendResponse")
    public String sedpSignAndSend(
        @WebParam(name = "taxId", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String taxId,
        @WebParam(name = "moduleType", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
                ModuleType moduleType,
        @WebParam(name = "documentXML", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String documentXML,
        @WebParam(name = "docType", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        GetDocumentType docType);

    /**
     * SEDP:Internal Use
     * 
     * @param documentKeys
     * @param moduleType
     * @param taxId
     * @param docType
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.ArrayOfNDocument
     */
    @WebMethod(operationName = "SEDP_GetDocument", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/SEDP_GetDocument")
    @WebResult(name = "SEDP_GetDocumentResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "SEDP_GetDocument", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.SEDPGetDocument")
    @ResponseWrapper(localName = "SEDP_GetDocumentResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.SEDPGetDocumentResponse")
    public ArrayOfNDocument sedpGetDocument(
        @WebParam(name = "taxId", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String taxId,
        @WebParam(name = "moduleType", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
                ModuleType moduleType,
        @WebParam(name = "docType", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        GetDocumentType docType,
        @WebParam(name = "documentKeys", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        ArrayOfDocumentKey documentKeys);

    /**
     * SEDP:Internal Use
     * 
     * @param moduleType
     * @param taxId
     * @param docType
     * @param documentUUID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SEDP_GetHtml", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/SEDP_GetHtml")
    @WebResult(name = "SEDP_GetHtmlResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "SEDP_GetHtml", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.SEDPGetHtml")
    @ResponseWrapper(localName = "SEDP_GetHtmlResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.SEDPGetHtmlResponse")
    public String sedpGetHtml(
        @WebParam(name = "taxId", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String taxId,
        @WebParam(name = "moduleType", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
                ModuleType moduleType,
        @WebParam(name = "docType", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        GetDocumentType docType,
        @WebParam(name = "documentUUID", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String documentUUID);

    /**
     * Sistemin durumunu kontrol eder
     * 
     * @param checkSystemKey
     * @return
     *     returns tr.com.netle.edonusum.ortakfatura.ver1.CheckSystemResult
     */
    @WebMethod(operationName = "CheckSystem", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/CheckSystem")
    @WebResult(name = "CheckSystemResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "CheckSystem", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.CheckSystem")
    @ResponseWrapper(localName = "CheckSystemResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.CheckSystemResponse")
    public CheckSystemResult checkSystem(
        @WebParam(name = "checkSystemKey", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String checkSystemKey);

    /**
     * Ortak: e-fatura ya da e-arsiv islevlerini kullanmadan once guvenlik denetimi icin alinmasi gereken token degerini getirir
     * 
     * @param password
     * @param moduleType
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateUserToken", action = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/CreateUserToken")
    @WebResult(name = "CreateUserTokenResult", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
    @RequestWrapper(localName = "CreateUserToken", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.CreateUserToken")
    @ResponseWrapper(localName = "CreateUserTokenResponse", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/", className = "tr.com.netle.edonusum.ortakfatura.ver1.CreateUserTokenResponse")
    public String createUserToken(
        @WebParam(name = "userName", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String userName,
        @WebParam(name = "password", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
        String password,
        @WebParam(name = "moduleType", targetNamespace = "http://www.netle.com.tr/EDonusum/OrtakFatura/Ver1.0/")
                ModuleType moduleType);

}
